### ISSUE TITLE
Mobile version of the website to be completed

### ISSUE THREAD

**Issue by luztherose** [luztherose/firstProject#1]
**TODO**

*Make the website fully resposive*

- [ ] Make it adaptable to small screens.

- [ ] make it adaptable to medium size screens.

- [ ] Add it JavaScript functionality.

🎉 👩‍💻 🎊 🙆 😍 

@amejia481

**Comment by Amejia481** [comment]
Let's work on that ❤️
